version: '3.5'

volumes:
  data:


services:
  database:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=test123
    volumes:
      - data:/var/lib/postgresql/data
